apiVersion: apps/v1
kind: Deployment
metadata:
  name: liberty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liberty
  template:
    metadata:
      labels:
        app: liberty
    spec:
      containers:
      - name: liberty
        image: docker.io/tkoshimoto/sample2:0.1
        ports:
        - containerPort: 9080