apiVersion: v1
kind: Service
metadata:
  name: liberty
  labels:
    app: liberty
spec:
  selector:
    app: liberty
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 9080
