FROM registry.redhat.io/ubi7/ubi:7.9
LABEL maintainer="tkoshimoto@yahoo.co.jp" \
      description="A custom Apache container based on UBI 8.2"
ENV PORT 8080
RUN yum install -y httpd && \
    yum clean all
RUN sed -ri -e "s/^Listen 80/c\Listen ${PORT}" /etc/httpd/conf/httpd.conf && \
    chown -R 48:48 /var/log/httpd && \
    chown -R 48:48 /run/httpd
EXPOSE ${PORT}
USER apache
ADD index.html /var/www/html/
CMD ["httpd", "-D", "FOREGROUND"]
